server:
  port: 8022
spring:
#Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: asas6302@gmail.com
    password: lnovfybpxcfmpbiz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#/Mail
#JSP 경로 추가
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#/JSP 경로추가
  datasource:
#     기본경로 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
#     /기본경로
#    logback
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
#    /logback
    username: root
    password:
#    xml resultType 
mybatis:
  type-aliases-package: com.example.demo.dto
#    /xml resultTyp
#    logback
custom:
#Mail
  siteMainUri: http://localhost:8022/
  siteName: Garden
  emailFrom: no-reply@localhost
  emailFromName: Garden
#/Mail
  genFileDirPath: C:/work/tq
  logging:
    dir: LOG_PATH_IS_UNDEFINED
    level: debug
# 로거 출력 : debug / 로거 미출력 : info
#    /logback